[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''\/localhost.*\.key$''',
                
    # Ignore anything with the word funkymonkey anywhere in the path
    '''foobar''','''yPsw5e6ab4bvAGe5H'''

    # Ignore some long path
    '''examples\/some\/long\/path\/server.key$''',
  ]
        
  # Ignore based on any subset of the line
  regexes = [
    # Ignore lines containing pickles
    '''LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JS''',
  ]